project_name: morrigan
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: .
    ldflags:
      - -s -w -X morrigan/cmd.Version=v{{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - maintainer: Naohiro CHIKAMATSU <n.chika156@gmail.com>
    description: morrigan - Penetration Tool Set
    homepage: https://github.com/nao1215/morrigan
    license: MIT License
    formats:
      - deb
      - rpm
      - apk
brews:
  - name: morrigan
    description: morrigan - Penetration Tool Set
    license: MIT
    repository:
      owner: nao1215
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
