project_name: morrigan
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: .
    ldflags:
      - -s -w -X morrigan/internal/cmdinfo.Version=v{{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - "386"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
